### ISSUE TITLE
Example for updating Google Sheet?

### ISSUE THREAD

**Issue by nwittwer** [spenwall/gridsome-source-google-sheets#12]
Thanks for writing this plugin! Was wondering if you might have ideas for how to also update a Google Sheet using GraphQL? Is it out of the scope of this plugin?

**Comment by spenwall** [comment]
Ya sorry this can only read. Not sure even how to go about writing back to sheets.

**Comment by nwittwer** [comment]
It's possible to write to a range of cells like so: https://github.com/yyx990803/build-your-own-mint/blob/master/lib/update.js using the `googleapis` Node module. 

```js
const { google } = require('googleapis')
const moment = require('moment')
const oAuth2Client = require('./googleClient')

oAuth2Client.setCredentials({
  access_token: process.env.SHEETS_ACCESS_TOKEN,
  refresh_token: process.env.SHEETS_REFRESH_TOKEN,
  scope: process.env.SHEETS_SCOPE,
  token_type: process.env.SHEETS_TOKEN_TYPE,
  expiry_date: process.env.SHEETS_EXPIRY_DATE
})

const sheets = google.sheets({
  version: 'v4',
  auth: oAuth2Client
})

exports.updateSheet = async function(updates) {
  sheets.spreadsheets.values.batchUpdate({
    spreadsheetId: process.env.SHEETS_SHEET_ID,
    resource: {
      valueInputOption: `USER_ENTERED`,
      data: updates.map(p => ({
        range: p.range,
        values: p.values
      }))
    }
  }, (err, res) => {
    if (err) {
      return console.log('Update failed: ', err)
    }
    console.log(`Success! ${res.data.totalUpdatedCells} cells updated.`)
  })
}
```

I think getting this to work with Gridsome would require having a separate API server with the Google OAuth credentials, which you could call from the [Gridsome client-side](https://gridsome.org/docs/client-side-data/#fetch-from-rest-api). There's more details and starter code [here](https://github.com/yyx990803/build-your-own-mint#google-sheets). But even if you were able to update the data on Google Sheets, the data you see in Gridsome is still cached... so you'd need to trigger a new build in production just to see the new data?

I've ultimately switched to using Nuxt for my project, because I need to read and write to Google Sheets in real-time, whereas it seems like Gridsome is better for use cases like eCommerce which don't need to be updated as frequently. Feel free to close this ticket :)
