### ISSUE TITLE
Only importing first row from sheet

### ISSUE THREAD

**Issue by NickStees** [spenwall/gridsome-source-google-sheets#3]
In my GraphQL explorer I was **only getting 1 row imported**, and I noticed an odd warning in the console when running 'gridsome develop', the warning was `googleSheet > Failed to add node: Duplicate key for property path: /`

So I don't believe the route is truly optional. 

I got it working by changing the route config to 
`route: "googleSheet/:Col1", //Optional - omit if not using routes`

That finally got the second row to show up in GraphQL

Maybe you should change the default config to have a default route?

**Comment by spenwall** [comment]
You're right. I did have a bug on that. It should be fixed in v 0.3.1. Thanks for reporting.

Please let me know if you have any other issues.
